# ### wylogowanie
# GET http://localhost:3000/api/logout HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6Im5hbWUiLCJsYXN0TmFtZSI6Imxhc3ROYW1lIiwiZW1haWwiOiJuYW1lM0BlbWFpbC5wbCIsInBhc3N3b3JkIjoiJDJhJDEwJEgwRFFSbXBPUkpIa0lPRVJUZzhEaXVGUHk1NldpS3paR1ROcDlhR0F0Y0tlLlVkM1cvREl1IiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODU1MzEzMDgsImV4cCI6MTY4NTUzMTYwOH0.UgKGrs7kCdSijGHGxDnUYLwtGD8jf0FRQ7CVDrlhYks