### post image i nazwy albumu
POST http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkVTdRWDY0a1oucUhkbFpRWFUvZ2RILlVtZjc0dUVrbG14c0hkY2FiYklVLjllZWFKa2piaEsiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjIzMzc5OSwiZXhwIjoxNjg2MjM0Mzk5fQ.5_NKcX3LFnC93AFBdohF80l8nJMYjRXLX8sIa8W0HAQ
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ../input.png

------FormBoundary1234

### get jsona wszystkich zdjęć
GET http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

### get jsona jednego zdjęcia
GET http://localhost:3000/api/photos/2 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

### patch jsona
PATCH http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s
content-type: application/json

{
  "id": 3,
  "status": "zmienione 52"
}


### delete image i jsona
DELETE http://localhost:3000/api/photos/4 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s


### aktualizacja danych zdjęcia o nowy tag, id to id zdjęcia, tag to istniejący tag
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

{
  "id": 1,
  "tag": {
      "name": "#style"
  }
}


### aktualizacja danych zdjęcia o tablicę nowych tag-ów
PATCH http://localhost:3000/api/photos/tags/mass HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

{
  "id": 5,
  "tags": [
    {"name": "#nowytag"},
    {"name": "#cute"}
  ]
}


### pobranie tagów danego zdjęcia
GET http://localhost:3000/api/photos/tags/6 HTTP/1.1


### dane json zdjęć z wybranego folderu (nie bedzie dzialac z polskimi znakami prawdopodobnie)
GET http://localhost:3000/api/photos/album123