### post image i nazwy albumu
POST http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkR3B4UDJxOVBVU2VIS3VrSy5SaG91ZXNLREUyRVY0eTIucG81QjEwZnpwa1VpbE5VUFZxb1ciLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjU4NTU4MSwiZXhwIjoxNjg2NTg2MTgxfQ.lX4uI1XCurPr3q5xS0mi0n2fMGfMKQZAsALKV4U5xXU
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ../input.png

------FormBoundary1234

### get jsona wszystkich zdjęć
GET http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

### get jsona jednego zdjęcia
GET http://localhost:3000/api/photos/2 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

### patch jsona
PATCH http://localhost:3000/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s
content-type: application/json

{
  "id": 3,
  "status": "zmienione 52"
}


### delete image i jsona
DELETE http://localhost:3000/api/photos/4 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s


### aktualizacja danych zdjęcia o nowy tag, id to id zdjęcia, tag to istniejący tag
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

{
  "id": 1,
  "tag": {
      "name": "#style"
  }
}


### aktualizacja danych zdjęcia o tablicę nowych tag-ów
PATCH http://localhost:3000/api/photos/tags/mass HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOHk3dGFpYlRzMUkyemZMNnQ0RVBidS9lcndlT3V6eWVkbno1UHRSU2dBMUQ0d1lwSDQuQ1MiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjEzNjgxNiwiZXhwIjoxNjg2MTM3MTE2fQ.bHVYK6KE0obzhaLxsm1esVDy7YbUe0OhPq79i9RNy7s

{
  "id": 5,
  "tags": [
    {"name": "#nowytag"},
    {"name": "#cute"}
  ]
}


### pobranie tagów danego zdjęcia
GET http://localhost:3000/api/photos/tags/6 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEiLCJsYXN0TmFtZSI6IjEiLCJlbWFpbCI6IjFAMSIsInBhc3N3b3JkIjoiJDJhJDEwJHg3cFJaMTQuTi91T2VpSFpTQ1luT3VqQnhvNTF6SmFaZGI3RnNqUnc0dlI3amVkcTZuZHA2IiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODYyMjYwNDksImV4cCI6MTY4NjIyNjY0OX0.WWhvItJlG9s83QyNBgRKi2ZwnYjsVy9VuONN-eel93s


### dane json zdjęć z wybranego folderu (nie bedzie dzialac z polskimi znakami prawdopodobnie)
GET http://localhost:3000/api/photos/album123
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEiLCJsYXN0TmFtZSI6IjEiLCJlbWFpbCI6IjFAMSIsInBhc3N3b3JkIjoiJDJhJDEwJHg3cFJaMTQuTi91T2VpSFpTQ1luT3VqQnhvNTF6SmFaZGI3RnNqUnc0dlI3amVkcTZuZHA2IiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODYyMjYwNDksImV4cCI6MTY4NjIyNjY0OX0.WWhvItJlG9s83QyNBgRKi2ZwnYjsVy9VuONN-eel93s
