### get image file by id
GET http://localhost:3000/api/getfile/1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkVTdRWDY0a1oucUhkbFpRWFUvZ2RILlVtZjc0dUVrbG14c0hkY2FiYklVLjllZWFKa2piaEsiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjI0MzA4OCwiZXhwIjoxNjg2MjQzNjg4fQ.0jGVxtnToVqh1CIgSE8srQOGhsd3b3LV_jUKVJhUgCs


### zmienione zdjęcie by id, na koncu musi byc uzyta nazwa filtra
GET http://localhost:3000/api/getfile/1/tint
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkd2FXSTFaMzVpcFBHejNmb0tuWXh1ZWtjNmdLRWxsV3JTeklJaTlwRks1VTBwbzhQSTg1YWUiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjMxNzE1MywiZXhwIjoxNjg2MzE3NzUzfQ.QZvPugZzWUjRTHN5zlQBpPtm1zyQyIN9x9sil-GPwVg
