### pobranie danych usera do wyświetlenia w profilu
GET http://localhost:3000/api/profile HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IjIiLCJsYXN0TmFtZSI6IjIiLCJlbWFpbCI6IjJAMiIsInBhc3N3b3JkIjoiJDJhJDEwJHkwSjBsL3U0Zkw4cWZIUkc2cmFoaHVaWmxqbEU1S0c1c3FQOGtPUk9rU0IwU1l0RWNkN3AuIiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODYzMDI2MDksImV4cCI6MTY4NjMwMzIwOX0.HBwe07GZbuZsybFLxAODCw2KEP4jzPnqefasBP8vf5A


### aktualizacja danych usera w jego profilu
PATCH http://localhost:3000/api/profile HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEiLCJsYXN0TmFtZSI6IjEiLCJlbWFpbCI6IjFAMSIsInBhc3N3b3JkIjoiJDJhJDEwJHg3cFJaMTQuTi91T2VpSFpTQ1luT3VqQnhvNTF6SmFaZGI3RnNqUnc0dlI3amVkcTZuZHA2IiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODYyMjYwNDksImV4cCI6MTY4NjIyNjY0OX0.WWhvItJlG9s83QyNBgRKi2ZwnYjsVy9VuONN-eel93s

{ 
  "name": "name60",
  "lastName": "lastName60"
}

### wysłanie zdjęcia profilowego, kolejność nagłówków jest tutaj ważna
POST http://localhost:3000/api/profile HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEiLCJsYXN0TmFtZSI6IjEiLCJlbWFpbCI6IjFAMSIsInBhc3N3b3JkIjoiJDJhJDEwJHg3cFJaMTQuTi91T2VpSFpTQ1luT3VqQnhvNTF6SmFaZGI3RnNqUnc0dlI3amVkcTZuZHA2IiwiY29uZmlybWVkIjp0cnVlLCJpYXQiOjE2ODYyMjYwNDksImV4cCI6MTY4NjIyNjY0OX0.WWhvItJlG9s83QyNBgRKi2ZwnYjsVy9VuONN-eel93s
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./input2.png

------FormBoundary1234