###  pobranie jsona wszystkich userow
GET http://localhost:3000/api/userdata HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOVAwbzJLbW5HUDJsUndSdmlWM2dhdXRZc3JvcThtNUIvQ25kcURkZC9vTWMvdUE3U085amkiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjMwNTU1NywiZXhwIjoxNjg2MzA2MTU3fQ.B2y9ta4KxdA5YTs_gBHvzOce3BTayWqGSXCBOlRCFzE


###  pobranie jsona usera po id
GET http://localhost:3000/api/userdata/0 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IjEyMyIsImxhc3ROYW1lIjoiMTIzIiwiZW1haWwiOiIxMjNAMTIzIiwicGFzc3dvcmQiOiIkMmEkMTAkOVAwbzJLbW5HUDJsUndSdmlWM2dhdXRZc3JvcThtNUIvQ25kcURkZC9vTWMvdUE3U085amkiLCJjb25maXJtZWQiOnRydWUsImlhdCI6MTY4NjMwNTU1NywiZXhwIjoxNjg2MzA2MTU3fQ.B2y9ta4KxdA5YTs_gBHvzOce3BTayWqGSXCBOlRCFzE
